devices:
  10.211.34.5:
    connections:
      cli:
        ip: 10.211.34.5
        protocol: ssh
    credentials:
      default:
        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKh}'
        username: svc_telecom
      enable:
        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKh}'
    os: iosxe
    type: iosxe
