devices:
  CD1088-SW05:
    connections:
      cli:
        ip: 10.211.34.5
        protocol: ssh
    credentials:
      default:
        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
        username: svc_telecom
      enable:
        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
    os: iosxe
    type: iosxe
#  CD1088-SW11:
#    connections:
#      cli:
#        ip: 10.211.34.11
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW12:
#    connections:
#      cli:
#        ip: 10.211.34.12
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW13:
#    connections:
#      cli:
#        ip: 10.211.34.13
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW14:
#    connections:
#      cli:
#        ip: 10.211.34.14
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW15:
#    connections:
#      cli:
#        ip: 10.211.34.15
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW16:
#    connections:
#      cli:
#        ip: 10.211.34.16
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW17:
#    connections:
#      cli:
#        ip: 10.211.34.17
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW18:
#    connections:
#      cli:
#        ip: 10.211.34.18
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW19:
#    connections:
#      cli:
#        ip: 10.211.34.19
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW20:
#    connections:
#      cli:
#        ip: 10.211.34.20
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW21:
#    connections:
#      cli:
#        ip: 10.211.34.21
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW22:
#    connections:
#      cli:
#        ip: 10.211.34.22
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW23:
#    connections:
#      cli:
#        ip: 10.211.34.23
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW24:
#    connections:
#      cli:
#        ip: 10.211.34.24
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW25:
#    connections:
#      cli:
#        ip: 10.211.34.25
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#  CD1088-SW26:
#    connections:
#      cli:
#        ip: 10.211.34.26
#        protocol: ssh
#    credentials:
#      default:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#        username: svc_telecom
#      enable:
#        password: '%ENC{w4TCrMKSwqfDlsKPw5HCmMK0wpHCpsKhwrQ=}'
#    os: iosxe
#    type: iosxe
#